version: "3.8"
services:

  db:
    image: postgres:13.0-alpine
    container_name: itm_postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env


  backend:
    image: leenominai/backend
    container_name: itm_backend
    restart: always
    volumes:
      - static_value:/backend/itm_backend/static/
      - media_value:/backend/itm_backend/media/
    depends_on:
      - db
    env_file:
      - ./.env


  frontend:
    image: leenominai/frontend
    container_name: itm_frontend
    volumes:
      - ./frontend/result_build:/app/dist/


  nginx:
    image: nginx:1.21.3-alpine
    container_name: itm_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - ./frontend/result_build:/usr/share/nginx/html/
    depends_on:
      - backend

volumes:
  postgres_data:
  static_value:
  media_value:
